lr: 5e-6
epochs: 10
random_state: 42
weight_decay: 0.01
batch_size: 8
train_size: 0.7
train_path: data/train-00000-of-00001.parquet
validation_path: data/validation-00000-of-00001.parquet
codebert_model_name: huggingface/CodeBERTa-small-v1
freeze_layers: 2
codebert_model_path: models/baseline_codebert_model.pth
sql_index_path: models/sql_baseline_index.pt
max_length: 80
patience: 5
llm_model: claude-haiku-4-5
