lr: 1e-5
epochs: 30
random_state: 42
weight_decay: 0.01
batch_size: 8
train_size: 0.7
train_path: data/train-00000-of-00001.parquet
validation_path: data/validation-00000-of-00001.parquet
codebert_model_name: microsoft/codebert-base
freeze_layers: 10
codebert_model_path: models/codebert_model.pth
sql_index_path: models/sql_index.pt
max_length: 81
patience: 5
llm_model: claude-haiku-4-5
