name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.head_branch == 'master'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build imagen
        run: |
          docker build \
            -f Dockerfile.api \
            -t ghcr.io/${{ github.repository_owner }}/text-to-sql-api:latest \
            .

      - name: Push imagen
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/text-to-sql-api:latest

      - name: Deploy OVH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/text-to-sql-api:latest

            docker stop text-to-sql-api || true
            docker rm text-to-sql-api || true

            docker run -d \
              --name text-to-sql-api \
              --restart unless-stopped \
              -p 80:8000 \
              -e WANDB_API_KEY=${{ secrets.WANDB_API_KEY }} \
              ghcr.io/${{ github.repository_owner }}/text-to-sql-api:latest